# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["golang.org/x/net/idna"]

[prune]
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/cyverse-de/condor-launcher"

[[constraint]]
  branch = "master"
  name = "github.com/cyverse-de/vaulter"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.7.1"

[[constraint]]
  name = "gopkg.in/cyverse-de/messaging.v3"
  version = "3.0.0"

[[constraint]]
  name = "gopkg.in/cyverse-de/model.v1"
  version = "1.1.0"

[[constraint]]
  name = "gopkg.in/cyverse-de/model.v2"
  version = "2.4.0"
